[package]
name = "crate_python"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.23.3" }
serde = { version = "1.0.217", features = ["derive"] }
build-print = "0.1.1"
cmd_lib = "1.9.5"
toml = "0.8.19"
pyo3-build-config = { version = "0.23.4", features = ["resolve-config"] }
