[package]
name = "python_bin"
version = "0.1.0"
edition = "2024"

[build-dependencies]
crate_python = { version = "0.1.0", path = "../../crate_python" }
python_lib = { version = "0.1.0", path = "../python_lib" }
