[package]
name = "python_bin"
version = "0.1.0"
edition = "2024"

[build-dependencies]
crate_python = { version = "0.1.0", path = "../../crate_python" }
pylib = { version = "0.1.0", path = "../pylib" }

[dependencies]
pyo3 = { version = "0.23.4", features = ["auto-initialize"] }
